stages:
  - deploy

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - rsync -av --delete ./ /var/www/vue-components.dash-game.thrill.house
  environment:
    name: staging
    url: https://vue-components.dash-game.thrill.house
  only:
  - master