import bandwidth from '../assets/img/bandwidth.svg';
import confidence from '../assets/img/confidence.svg';
import data from '../assets/img/data.svg';
import economy from '../assets/img/economy.svg';
import influence from '../assets/img/influence.svg';
import neutral from '../assets/img/neutral.svg';
import science from '../assets/img/science.svg';
import society from '../assets/img/society.svg';

require('../assets/img/abilities/buzzie.svg');
require('../assets/img/abilities/dungeoneer.svg');
require('../assets/img/abilities/foreweather.svg');
require('../assets/img/abilities/gamebryo.svg');
require('../assets/img/abilities/injoke.svg');
require('../assets/img/abilities/movemental.svg');
require('../assets/img/abilities/proposalis.svg');
require('../assets/img/abilities/reright.svg');
require('../assets/img/abilities/scrypto.svg');
require('../assets/img/abilities/surveysis.svg');
require('../assets/img/abilities/tutora.svg');
require('../assets/img/abilities/tweetment.svg');
